### ISSUE TITLE
Clicking the consent banner button does nothing, and a 400 error is thrown by the server (OSOE-108)

### ISSUE THREAD

**Issue by 0liver** [Lombiq/Orchard-Privacy#15]
I've just noticed this yesterday during testing the consent banner in OSOCE.NuGet:

When you click the button, visually nothing happens. A request it sent to the server, but the response is a 400 HTTP error.

@Piedone What else should I with this bug?

**Comment by Piedone** [comment]
Please share a screen recording since I can't reproduce this.

**Comment by 0liver** [comment]
![lombiq-privacy-consent-banner-no-action](https://user-images.githubusercontent.com/164360/164784298-f50fef06-faad-45dd-a481-b2b4925af8c1.gif)

And here's an HAR of the broken request:
[borken-request.har.zip](https://github.com/Lombiq/Orchard-Privacy/files/8543672/borken-request.har.zip)

**Comment by Piedone** [comment]
I see. I think this only happens if you do this:

1. Enable the Consent Banner feature.
2. Try to click that button when the banner is shown within the same user sessoin.

If you log out and in, it should work, as well as if you do this with an anonymous or newly registered user.

**Comment by 0liver** [comment]
That's exactly what I did.

But why does it break/not work?

**Comment by Piedone** [comment]
OK then.

This is something the one picking this up needs to investigate :).

**Comment by dministro** [comment]
Based on the har, the content length is 0. This can occur if the value of '__RequestVerificationToken' property of data parameter of $.post() is undefined.

I tried to reproduce this issue, as described by @Piedone , but everything worked fine for me.

As described in [Prevent Cross-Site Request Forgery (XSRF/CSRF) attacks in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/anti-request-forgery?view=aspnetcore-6.0) Razor Pages are automatically protected from XSRF/CSRF, and hidden input elements are automatically injected to the rendered forms.

So I changed the the theme to a liquid based one, and the error came up. With razor based theme there is no error.

So the exact repruduction steps of this issue(based on my experience and docs):
1. Select liquid based theme
2. Enable the Consent Banner feature.
3. Try to click that button when the banner is shown within the same user session.
@0liver , @Piedone could you confirm this?

In the docs I found no guaranty to the <input name="__RequestVerificationToken"...> will be always injected.
I think we can resolve this issue if we request a csrf token over a IAntiforgery instance, and pass it's value to $.post().

**Comment by Piedone** [comment]
Ah, so [this won't find the token](https://github.com/Lombiq/Orchard-Privacy/blob/dev/Views/Lombiq.Privacy.ConsentBanner.cshtml#L69) since it implicitly depends on Razor. That seems plausible.

**Comment by 0liver** [comment]
Nice detective work, @dministro! 🕵🏼

**Comment by dministro** [comment]
> Ah, so [this won't find the token](https://github.com/Lombiq/Orchard-Privacy/blob/dev/Views/Lombiq.Privacy.ConsentBanner.cshtml#L69) since it implicitly depends on Razor. That seems plausible.

Yes, in some cases it won't find the token, and it depends on Razor and we need a form with method="post".
Requirements described here: [Antiforgery in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/anti-request-forgery?view=aspnetcore-6.0#antiforgery-in-aspnet-core)
